# Generated by Django 4.2.6 on 2024-05-15 01:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import operation.deal.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('organization', '0001_initial'),
        ('product', '0001_initial'),
        ('company', '0001_initial'),
        ('currency', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_name', models.CharField(max_length=100, null=True, unique=True)),
                ('deal_source', models.CharField(choices=[('website', 'Website'), ('whatsapp', 'Whatsapp'), ('direct_mail', 'Direct Mail'), ('phone_call', 'Phone Call'), ('in_person', 'In Person'), ('social_media', 'Social Media')], max_length=50)),
                ('primary_email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('title', models.CharField(choices=[('ceo', 'CEO'), ('company_rep', 'Company Representative'), ('independent_professional', 'Independent Professional'), ('entrepreneur', 'Entrepreneur'), ('student', 'Student')], max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('mobile_phone', models.CharField(blank=True, max_length=20)),
                ('company_name', models.CharField(max_length=255)),
                ('company_email', models.EmailField(max_length=254)),
                ('company_phone', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('industry', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('non_profit', 'Non-Profit')], max_length=20)),
                ('description', models.TextField(validators=[django.core.validators.MaxLengthValidator(280)])),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('start_date_time', models.DateTimeField(blank=True, help_text='Please use the following format: <em>YYYY-MM-DD</em>.', null=True)),
                ('end_date_time', models.DateTimeField(blank=True, help_text='Please use the following format: <em>YYYY-MM-DD</em>.', null=True)),
                ('extended_end_date_time', models.DateTimeField(blank=True, help_text='Please use the following format: <em>YYYY-MM-DD</em>.', null=True)),
                ('actual_completion_date', models.DateTimeField(blank=True, null=True)),
                ('stage', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('dorman', 'Dorman'), ('close_win', 'Close Win'), ('close_lost', 'Close Lost')], default='new', max_length=20)),
                ('is_closed', models.BooleanField(default=False)),
                ('erased', models.BooleanField(default=False)),
                ('assigned_to', models.ForeignKey(on_delete=models.SET(operation.deal.models.get_sentinel_user), related_name='assigned_deal', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_deals', to='client.client')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_deals', to='company.company')),
                ('country', models.ForeignKey(limit_choices_to={'is_selected': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='country.country')),
                ('created_by', models.ForeignKey(on_delete=models.SET(operation.deal.models.get_sentinel_user), related_name='created_deal', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='currency.currency')),
                ('last_modified_by', models.ForeignKey(on_delete=models.SET(operation.deal.models.get_sentinel_user), related_name='last_modified_deal', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal', to='organization.organization')),
            ],
        ),
        migrations.CreateModel(
            name='DealProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cotizacion_url', models.URLField(blank=True, null=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_product', to='deal.deal')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_product', to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='DealTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('stage', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('is_closed', models.BooleanField(default=False)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_dealtask', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_dealtask', to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deal_dealtask', to='deal.deal')),
                ('deal_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_dealtask', to='deal.dealproduct')),
                ('last_modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modified_dealtask', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_dealtask', to='organization.organization')),
                ('parent_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_dealtask', to='deal.dealtask')),
            ],
        ),
    ]
