# Generated by Django 4.2.6 on 2024-05-15 01:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import operation.company.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_email', models.EmailField(max_length=254)),
                ('company_phone', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('industry', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('non_profit', 'Non-Profit')], max_length=20)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('erased', models.BooleanField(default=False)),
                ('is_client', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=models.SET(operation.company.models.get_sentinel_user), related_name='created_company', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(on_delete=models.SET(operation.company.models.get_sentinel_user), related_name='last_modified_company', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_company', to='organization.organization')),
            ],
        ),
    ]
